# Generated by Django 5.0.2 on 2024-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoviessite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='bio',
            field=models.CharField(default='hi', max_length=50),
        ),
    ]
