# Generated by Django 5.0.2 on 2024-05-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymoviessite', '0005_alter_users_created_at_alter_users_updated_at'),
    ]

    operations = [
    ]
